config {
  type: "view",
  schema: "staging",
  description: "Bicycle rental data corresponding to New York City",
}

select 
  id AS event_id,
	user_id,
	sequence_number,
	session_id,
	created_at,
	ip_address,
	city,
	state,
	postal_code,
	browser,
	traffic_source,
	uri AS web_link,
	event_type,
	{# Look in macros/macro_get_brand_name.sql to see how this function is defined #}
	{{ target.schema }}.get_brand_name(uri) AS brand_name
from 
${ref("events")}
